### ISSUE TITLE
Better tag with end statement support

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/HubL-Language-Extension#34]
This was partially fixed with https://github.com/williamspiro/HubL-Language-Extension/pull/21, but I realize some end tags have an underscore in them, like `end_widget_container`, compared to `endblock`, so the logic does not work for all tags with an end statement.

**Comment by williamspiro** [comment]
Fixing this would mean we can handle https://github.com/williamspiro/HubL-Language-Extension/pull/38 with auto-generation

**Comment by anthmatic** [comment]
In #44, I added some logic to lookup the end tag from the snippet and use that. In #54 I added auto-gen `dnd-*` tags.
