### ISSUE TITLE
Spelling issue on choice command for `placeholder`

### ISSUE THREAD

**Issue by ajlaporte** [HubSpot/HubL-Language-Extension#49]
Right now when generating a choice field, it has placeholder as `placerholder`this should be `placeholder`
Video below from John Fuller
https://slack-files.com/T22MX8Z8B-F01862R1KJ4-118ad6aac5

**Comment by anthmatic** [comment]
This was fixed in https://github.com/HubSpot/HubL-Language-Extension/commit/0a84a276e31c1a55c897eb9bcef8b958e6d67b20 and will be out in the next release
