### ISSUE TITLE
Integrate syntax highlighting into readme and highlight top level features

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/HubL-Language-Extension#58]
Syntax highlighting for HubL in html, css and JS should be called out somewhere in the very begging of the README.

Maybe something like:
>This is a HubL language extension for the Visual Studio Code IDE, allowing for 🚀 fast local HubSpot CMS Platform development in .html files. This extension supports:
>- HubL syntax highlighting for HTML, CSS, and JavaScript files
>- Autom-complete snippets for HubL tags, filters, functions, operators, expression tests and more
>- indentation...
>- HubL dleimeter auto-complete... - HubL comments - ...etc.
>For comprehensive HubL documentation, see the HubL docs.

We can also remove 
>For nice HubL syntax highlighting, install the Jinja scopes extension which lays on top of .html files.

**Comment by anthmatic** [comment]
Good call! Working on this in #57, will integrate this.
